# Generated by Django 3.2.5 on 2021-09-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='created_by',
            field=models.CharField(default='default-admin', max_length=100),
        ),
        migrations.AlterField(
            model_name='roles',
            name='modified_by',
            field=models.CharField(default='default-admin', max_length=50),
        ),
    ]
