# Generated by Django 3.2.5 on 2021-10-13 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_myuser_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roles',
            old_name='modified_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='active_status',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='modified_by',
        ),
        migrations.AddField(
            model_name='myuser',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='updated_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='roles',
            name='updated_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
